name: Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of the new mod loader release
        required: true
        default: "#.#.#"

jobs:
  package:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Copy required files into release directory
        shell: cmd
        run: |
          CALL _release.bat

      - name: Upload artifact 
        uses: actions/upload-artifact@v3
        with:
          name: ITB-ModLoader-${{ github.event.inputs.version }}.zip
          path: release/*
          retention-days: 7
          if-no-files-found: error
