name: Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of the new mod loader release
        required: true
        default: "#.#.#"

jobs:
  package:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Copy required files into release directory
        shell: cmd
        run: |
          IF EXIST release RMDIR /q /s release
          MKDIR release
          COPY /V lua5.1.dll release\lua5.1.dll
          COPY /V lua5.1-original.dll release\lua5.1-original.dll
          COPY /V opengl32.dll release\opengl32.dll
          COPY /V SDL2.dll release\SDL2.dll
          COPY /V SDL2-original.dll release\SDL2-original.dll
          COPY /V ftldat.dll release\ftldat.dll
          COPY /V itb_io.dll release\itb_io.dll
          COPY /V uninstall_modloader.bat release\uninstall_modloader.bat
          XCOPY mods release\mods /s /e /i
          XCOPY scripts release\scripts /s /e /i
          XCOPY resources release\resources /s /e /i

      - name: Upload artifact 
        uses: actions/upload-artifact@v3
        with:
          name: ITB-ModLoader-${{ github.event.inputs.version }}.zip
          path: release/*
          retention-days: 7
          if-no-files-found: error
